import localFont from "next/font/local";
import "./globals.css";
import Cube from "@/components/layout/Cube";
import { ProfileProvider } from "./context/ProfileContext";
import Header from "@/components/layout/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4072792689868937"
     crossorigin="anonymous"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0B101B]`}
      >
        <div className='absolute -top-16 right-48'>
          <Cube height='300' width='300' />
        </div>
        <div className='absolute top-64 left-0'>
          <Cube height='300' width='300' />
        </div>
        <ProfileProvider>
          <div className='h-screen'>
            <Header />
          {children}
          </div>
          </ProfileProvider>
      </body>
    </html>
  );
}
